- name: Setup Machine
  hosts: localhost
  become: yes # Use sudo to gain root privileges
  become_method: sudo
  vars:
    source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
    - name: Update Apt
      become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/install-ssh-keys.yml
    - include: tasks/git-setup.yml
    - include: tasks/core-setup.yml
    - include: tasks/node-setup.yml
    - include: tasks/install-npm-packages.yml
    # - include: tasks/zsh-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/stow-setup.yml

# Add any other tasks as needed
