- name: Decrypt files in a folder
  ansible.builtin.find:
    paths: ./gpg/ # Replace with the folder containing your vaulted files
    recurse: yes
    patterns: "*.*" # Adjust the file extension as needed
  register: vaulted_files

- name: Decrypt and move each encrypted file
  ansible.builtin.command: ansible-vault decrypt "{{ item.path }}" --output "{{ item.path | dirname }}/decrypted_{{ item.path | basename }}"
  with_items: "{{ vaulted_files.files }}"
  delegate_to: localhost # Ensure it's executed on the local machine
  when: item.path is defined
