- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "sergiorom92@gmail.com"
  tags:
    - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Sergio David Romero Maldonado"
  tags:
    - git-personal
